ServerEvents.recipes(e => {
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_palis_crystal",
        "actuallyadditions:palis_crystal_block",
        ['minecraft:potion[potion_contents={potion:"minecraft:water"}]',
         "cornflower",
         "smooth_stone",
         "lapis_block"],
        4000,
        Color.BLUE.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_restonia_crystal",
        "actuallyadditions:restonia_crystal_block",
        ["sweet_berries", 
         "rose_bush",
         "granite",
         "redstone_block"

        ],
        4000,
        Color.RED.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_diamatine_crystal",
        "actuallyadditions:diamatine_crystal_block",
        ["tropical_fish", 
         "warped_fungus",
         "deepslate",
         "diamond_block"

        ],
        4000,
        Color.DARK_AQUA.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_void_crystal",
        "actuallyadditions:void_crystal_block",
        ["dried_kelp", 
         "wither_rose",
         "blackstone",
         "obsidian"

        ],
        4000,
        Color.BLACK.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_enori_crystal",
        "actuallyadditions:enori_crystal_block",
        ["farmersdelight:milk_bottle", 
         "azure_bluet",
         "diorite",
         "iron_block"

        ],
        4000,
        Color.WHITE.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "actuallyadditions:empowered_emeradic_crystal",
        "actuallyadditions:emeradic_crystal_block",
        ["minecraft:poisonous_potato", 
         "minecraft:mangrove_propagule",
         "mossy_cobblestone",
         "emerald_block"

        ],
        4000,
        Color.GREEN.argb,
        100
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_alloy_plate",
        "netherite_block",
        ["nether_star", 
         "advanced_ae:quantum_alloy_block",
         "extendedae:entro_block",
         "irons_spellbooks:mithril_ingot"
        ],
        60000,
        Color.DARK_BLUE.argb,
        400
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_alloy",
        ["extendedae:entro_ingot",],
        ["advanced_ae:shattered_singularity", 
         "advanced_ae:shattered_singularity",
         "actuallyadditions:empowered_emeradic_crystal",
         "actuallyadditions:empowered_palis_crystal"
        ],
        40000,
        Color.DARK_BLUE.argb,
        180
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_helmet",
        ["hazennstuff:fireblossom_helmet",],
        ["advanced_ae:quantum_alloy_plate", 
         "advanced_ae:data_entangler",
         "powah:battery_nitro",
         "actuallyadditions:empowered_void_crystal_block"
        ],
        80000,
        Color.DARK_BLUE.argb,
        180
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_chestplate",
        ["hazennstuff:fireblossom_chestplate",],
        ["advanced_ae:quantum_alloy_plate", 
         "advanced_ae:data_entangler",
         "powah:battery_nitro",
         "actuallyadditions:empowered_void_crystal_block"
        ],
        80000,
        Color.DARK_BLUE.argb,
        180
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_leggings",
        ["hazennstuff:fireblossom_leggings",],
        ["advanced_ae:quantum_alloy_plate", 
         "advanced_ae:data_entangler",
         "powah:battery_nitro",
         "actuallyadditions:empowered_void_crystal_block"
        ],
        80000,
        Color.DARK_BLUE.argb,
        180
    )
    e.recipes.actuallyadditions.empowering(
        "advanced_ae:quantum_boots",
        ["hazennstuff:fireblossom_boots",],
        ["advanced_ae:quantum_alloy_plate", 
         "advanced_ae:data_entangler",
         "powah:battery_nitro",
         "actuallyadditions:empowered_void_crystal_block"
        ],
        80000,
        Color.DARK_BLUE.argb,
        180
    )
})